# Generated by Django 4.1.4 on 2022-12-19 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='main.musicion'),
        ),
    ]
